apiVersion: v1
kind: Secret
metadata:
  name: notifications-worker-secret
  namespace: fcg
  labels:
    app: notifications-worker
type: Opaque
stringData:
  ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=fcg_notifications_db;Username=fcg;Password=fcg_secret"
