apiVersion: v1
kind: Secret
metadata:
  name: fcg-shared-secret
  namespace: fcg
type: Opaque
stringData:
  Jwt__SecretKey: "UvPTu5UZIcSe0V1onJSNTWT579OHlmoxXA1flLgKpow="
  RabbitMq__Password: "guest"
