apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=fcg_catalog_db;Username=fcg;Password=fcg_secret"
